import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    nav: {
      home: 'Home',
      services: 'Services',
      spiderControl: 'Spider Control',
      roachCleanup: 'Roach Cleanup',
      communities: 'Communities',
      rodentControl: 'Rodent Control',
      bedBugTreatment: 'Bed Bug Treatment',
      fleaTickTreatment: 'Flea & Tick Treatment',
      mosquitoControl: 'Mosquito Control',
      sanCarlosPark: 'San Carlos Park',
      estero: 'Estero',
      bonitaSprings: 'Bonita Springs',
      serviceAreas: 'Service Areas',
    },
    header: {
      freeQuote: 'Free Quote',
      language: 'Language',
      darkMode: 'Dark Mode',
      lightMode: 'Light Mode',
    },
    banner: {
      text: 'Local • Licensed & Insured • Southwest Florida',
      phone: 'Call or text 239-227-0624',
    },
    hero: {
      badge: 'PEST CONTROL EXPERTS',
      title: 'Protecting Southwest Florida Homes Since 2015',
      titleNew: 'Southwest Florida\'s Most Trusted Pest Control — 247 5-Star Reviews',
      description: 'Veritas HomeServices LLC delivers integrity-driven pest control with transparent pricing, eco-friendly solutions, and a 100% satisfaction guarantee.',
      descriptionNew: 'Fast, effective, guaranteed. Starting at $35/mo.',
      getQuote: 'Get Free Quote',
      getQuoteNew: 'Get Free Quote',
      callNow: 'Call Now',
      learnMore: 'Learn More',
      trust: {
        licensed: 'Licensed & Insured',
        local: 'Local Family Owned',
        guarantee: 'Satisfaction Guaranteed',
      },
      trustBar: {
        reviews: '247 Reviews',
        license: 'Licensed JB500621',
        sameDay: 'Same-Day Service',
      },
      featuredOffers: 'Featured offers',
      monthlySpiderControl: 'Monthly Spider Control',
      from35mo: 'From $35/mo',
      spiderControlDesc: 'Exterior treatment + accessible web removal.',
      germanRoachCleanup: 'German Roach Clean-Up',
      from225: 'From $225',
      roachCleanupDesc: 'Structured four-visit program for qualifying residential properties.',
    },
    services: {
      title: 'Our Pest Control Services',
      subtitle: 'Comprehensive protection for your home and business',
      viewAll: 'View All Services',
      startingAt: 'Starting at',
      perMonth: '/month',
      featured: 'Most Popular',
      learnMore: 'Learn More',
      generalPestControl: 'General Pest Control',
      generalPestControlDesc: 'Routine residential protection with interior/exterior options for common household pest concerns, with recurring service available.',
      monthlySpiderControl: 'Monthly Spider Control',
      monthlySpiderControlDesc: 'Starting at $35/month. Exterior treatment plus removal of accessible spider webs on qualifying residential properties.',
      germanRoachCleanup: 'German Roach Clean-Up',
      germanRoachCleanupDesc: '4 visits from $225. Focused four-visit program for qualifying residential properties with German cockroach activity.',
      rodentControl: 'Rodent Control',
      rodentControlDesc: 'Inspection + targeted plan. Rodent inspection, monitoring and control recommendations based on conditions found.',
      bedBugTreatment: 'Bed Bug Treatment',
      bedBugTreatmentDesc: 'Property-specific treatment. Inspection and treatment recommendations based on confirmed activity and property conditions.',
      fleaTickTreatment: 'Flea & Tick Treatment',
      fleaTickTreatmentDesc: 'Targeted treatment. Focused service for flea and tick concerns, with preparation guidance when applicable.',
      mosquitoControl: 'Mosquito Control',
      mosquitoControlDesc: 'Outdoor mosquito service. Treatments focused on outdoor resting and breeding areas based on property conditions.',
      hoaPropertyManagement: 'HOA & Property Management',
      hoaPropertyManagementDesc: 'Custom service plans. Dependable scheduling, communication, common-area service and documentation for residential communities.',
    },
    whyVeritas: {
      title: 'Why Choose Veritas?',
      subtitle: 'We\'re not just another pest control company',
      reasons: [
        'Local family-owned business serving Southwest Florida',
        'Licensed, insured, and certified technicians',
        'Eco-friendly and pet-safe treatment options',
        'Transparent pricing with no hidden fees',
        '100% satisfaction guarantee on all services',
        'Same-day and emergency service available',
      ],
    },
    quickStart: {
      title: 'Ready to Get Started?',
      subtitle: 'Tell Us What You\'re Seeing',
      description: 'Get your free, no-obligation quote in under 2 minutes.',
      button: 'Get My Free Quote',
    },
    process: {
      title: 'Our Simple Process',
      subtitle: 'Getting Started Is Easy',
      steps: [
        { title: 'Free Inspection', description: 'We assess your property and identify pest issues at no cost.' },
        { title: 'Custom Plan', description: 'We create a tailored treatment plan for your specific needs.' },
        { title: 'Treatment', description: 'Our certified technicians apply eco-friendly solutions.' },
        { title: 'Follow-Up', description: 'We return to ensure pests are gone and prevent future issues.' },
      ],
    },
    hoa: {
      title: 'HOA & Community Management',
      subtitle: 'Partner with Veritas for reliable community pest control',
      badge: 'HOAs & PROPERTY MANAGERS',
      description: 'Flexible service plans can include scheduled pest prevention, common-area treatment, rodent bait-station monitoring, documented recommendations and callback terms defined by agreement.',
      cta: 'Community & Property Management Services',
      cardTitle: 'Built for property operations',
      features: [
        'Bulk pricing for communities and HOAs',
        'Dedicated account manager',
        'Scheduled preventive treatments',
        'Detailed service reports for boards',
        'Emergency response for common areas',
        'Resident communication support',
      ],
    },
    serviceAreas: {
      title: 'Areas We Serve',
      subtitle: 'Proudly serving Southwest Florida communities',
      areas: [
        { name: 'Fort Myers', description: 'Primary service area.', link: '/services' },
        { name: 'San Carlos Park', description: 'Local neighborhood service.', link: '/san-carlos-park' },
        { name: 'Estero', description: 'Residential pest-control options.', link: '/estero' },
        { name: 'Bonita Springs', description: 'Residential pest-control options.', link: '/bonita-springs' },
      ],
    },
    faq: {
      title: 'Frequently Asked Questions',
      subtitle: 'Frequently Asked Questions',
      questions: [
        {
          q: 'How often should I schedule pest control?',
          a: 'We recommend quarterly treatments for optimal prevention, but we offer monthly, bi-monthly, and one-time services based on your needs.',
        },
        {
          q: 'Are your treatments safe for pets and children?',
          a: 'Yes, we use EPA-approved, eco-friendly products that are safe for your family and pets once dried. We also offer fully organic options.',
        },
        {
          q: 'Do you offer emergency services?',
          a: 'Yes, we provide same-day and emergency service for urgent pest issues like wasp nests, rodent infestations, and more.',
        },
        {
          q: 'What pests do you treat?',
          a: 'We treat ants, spiders, roaches, rodents, bed bugs, fleas, ticks, mosquitoes, termites, and more. See our Services page for the full list.',
        },
        {
          q: 'Is there a contract required?',
          a: 'No contracts required for one-time services. Our recurring plans are month-to-month with no cancellation fees.',
        },
      ],
    },
    cta: {
      title: 'Don\'t Let Pests Take Over Your Home',
      subtitle: 'Get Your Free Pest Control Quote',
      description: 'Join hundreds of satisfied Southwest Florida homeowners who trust Veritas for reliable, effective pest control.',
      button: 'Get Free Quote',
      badge: 'READY TO GET STARTED?',
      buttonOnline: 'Request Service Online',
    },
    footer: {
      tagline: 'INTEGRITY & PROTECTION',
      quickLinks: 'Quick Links',
      services: 'Services',
      areas: 'Service Areas',
      contact: 'Contact Us',
      phone: '(239) 227-0624',
      email: 'info@veritashomeservices.com',
      hours: 'Mon-Fri: 8am-6pm | Sat: 9am-2pm',
      license: 'Licensed & Insured • Florida License #JF123456',
      rights: 'All rights reserved.',
      description: 'Residential pest control serving Fort Myers, San Carlos Park, Estero, Bonita Springs and nearby Southwest Florida communities.',
      fortMyers: 'Fort Myers',
      sanCarlosPark: 'San Carlos Park',
      estero: 'Estero',
      bonitaSprings: 'Bonita Springs',
      hoasPropertyManagers: 'HOAs & Property Managers',
      requestQuote: 'Request a Quote',
      copyright: '© 2026 Veritas HomeServices LLC. Pest Control Business License No. JB500621.',
      disclaimer: 'Service availability, scope and pricing depend on property conditions and written service terms. Pest-control service is intended to reduce and control covered pest activity and does not guarantee a completely pest-free environment.',
    },
    quoteForm: {
      title: 'Get Your Free Quote',
      subtitle: 'Fill out the form and we\'ll contact you within 24 hours',
      firstName: 'First Name',
      lastName: 'Last Name',
      email: 'Email',
      phone: 'Phone',
      address: 'Address',
      city: 'City',
      zipCode: 'ZIP Code',
      serviceType: 'Service Type',
      propertyType: 'Property Type',
      pestIssues: 'Pest Issues (select all that apply)',
      preferredDate: 'Preferred Date',
      comments: 'Additional Comments',
      residential: 'Residential',
      commercial: 'Commercial',
      submit: 'Submit Quote Request',
      submitting: 'Submitting...',
      success: 'Thanks! We\'ll contact you soon.',
      error: 'Something went wrong. Please try again.',
      required: 'Required',
    },
    aiAssistant: {
      title: 'Veritas AI Assistant',
      status: 'Online',
      placeholder: 'Ask about pests, services, or pricing...',
      quickReplies: [
        'Spider control pricing',
        'German roach program details',
        'Service areas covered',
        'Request a quote',
        'Business hours',
      ],
      quickRepliesAlt: [
        'What pests do you treat?',
        'How much does it cost?',
        'Is it safe for pets?',
        'Do you offer emergency service?',
        'What areas do you serve?',
      ],
      disclaimer: 'AI assistant provides general information. For specific advice, contact our team.',
      initialMessage: "Hi! I'm Veritas Assistant. How can I help you with your pest control needs today?",
      toggleText: 'AI Assistant',
      closeLabel: 'Close AI Assistant',
      openLabel: 'Open AI Assistant',
      sendLabel: 'Send message',
      typingLabel: 'AI is typing...',
      callLabel: 'Call',
      botResponses: {
        spider: "Monthly exterior spider control starts at $35/month for qualifying residential properties. This includes exterior treatment and accessible web removal.",
        roach: "Our German Roach Clean-Up is a structured 4-visit program starting at $225 for qualifying residential properties. Final pricing depends on infestation level and property conditions.",
        area: "We primarily serve Fort Myers, San Carlos Park, Estero, Bonita Springs, and nearby Southwest Florida communities.",
        quote: "You can request a free quote using our online form or by calling/texting 239-227-0624. I can help you with that!",
        hours: "We're available Monday-Friday 8am-6pm, Saturday 8am-12pm. For urgent issues, call 239-227-0624.",
        bedBug: "Bed bug treatment is property-specific. We start with an inspection and provide treatment recommendations based on confirmed activity and property conditions.",
        rodent: "Rodent control includes inspection, monitoring, and targeted recommendations based on conditions found. We also offer bait-station monitoring for communities.",
        fleaTick: "Flea & tick treatment is a focused service with preparation guidance when applicable. We treat based on your specific property conditions.",
        mosquito: "Mosquito control targets outdoor resting and breeding areas based on property conditions. It's a seasonal service for Southwest Florida.",
        hoa: "We offer custom service plans for HOAs and property managers including scheduled prevention, common-area treatment, documentation, and callback terms defined by agreement.",
        default: "I can help with pricing, services, service areas, quotes, or general questions. What would you like to know?",
      },
    },
  },
  es: {
    nav: {
      home: 'Inicio',
      services: 'Servicios',
      spiderControl: 'Control de Arañas',
      roachCleanup: 'Eliminación de Cucarachas',
      communities: 'Comunidades',
      rodentControl: 'Control de Roedores',
      bedBugTreatment: 'Tratamiento de Chinches',
      fleaTickTreatment: 'Pulgas y Garrapatas',
      mosquitoControl: 'Control de Mosquitos',
      sanCarlosPark: 'San Carlos Park',
      estero: 'Estero',
      bonitaSprings: 'Bonita Springs',
      serviceAreas: 'Áreas de Servicio',
    },
    header: {
      freeQuote: 'Cotización Gratis',
      language: 'Idioma',
      darkMode: 'Modo Oscuro',
      lightMode: 'Modo Claro',
    },
    banner: {
      text: 'Local • Licenciado y Asegurado • Suroeste de Florida',
      phone: 'Llama o envía mensaje al 239-227-0624',
    },
    hero: {
      badge: 'EXPERTOS EN CONTROL DE PLAGAS',
      title: 'Protegiendo Hogares del Suroeste de Florida Desde 2015',
      titleNew: 'El Control de Plagas Más Confiable del Suroeste de Florida — 247 Reseñas de 5 Estrellas',
      description: 'Veritas HomeServices LLC ofrece control de plagas impulsado por la integridad, con precios transparentes, soluciones ecológicas y garantía de satisfacción del 100%.',
      descriptionNew: 'Rápido, efectivo, garantizado. Desde $35/mes.',
      getQuote: 'Obtener Cotización Gratis',
      getQuoteNew: 'Obtener Cotización Gratis',
      callNow: 'Llamar Ahora',
      learnMore: 'Saber Más',
      trust: {
        licensed: 'Licenciado y Asegurado',
        local: 'Empresa Familiar Local',
        guarantee: 'Garantía de Satisfacción',
      },
      trustBar: {
        reviews: '247 Reseñas',
        license: 'Licenciado JB500621',
        sameDay: 'Servicio Mismo Día',
      },
      featuredOffers: 'Ofertas destacadas',
      monthlySpiderControl: 'Control Mensual de Arañas',
      from35mo: 'Desde $35/mes',
      spiderControlDesc: 'Tratamiento exterior + eliminación de telarañas accesibles.',
      germanRoachCleanup: 'Eliminación de Cucarachas Alemanas',
      from225: 'Desde $225',
      roachCleanupDesc: 'Programa estructurado de cuatro visitas para propiedades residenciales calificadas.',
    },
    services: {
      title: 'Nuestros Servicios de Control de Plagas',
      subtitle: 'Protección integral para su hogar y negocio',
      viewAll: 'Ver Todos los Servicios',
      startingAt: 'Desde',
      perMonth: '/mes',
      featured: 'Más Popular',
      learnMore: 'Saber Más',
      generalPestControl: 'Control General de Plagas',
      generalPestControlDesc: 'Protección residencial de rutina con opciones interior/exterior para plagas comunes del hogar, con servicio recurrente disponible.',
      monthlySpiderControl: 'Control Mensual de Arañas',
      monthlySpiderControlDesc: 'Desde $35/mes. Tratamiento exterior más eliminación de telarañas accesibles en propiedades residenciales calificadas.',
      germanRoachCleanup: 'Eliminación de Cucarachas Alemanas',
      germanRoachCleanupDesc: '4 visitas desde $225. Programa enfocado de cuatro visitas para propiedades residenciales calificadas con actividad de cucarachas alemanas.',
      rodentControl: 'Control de Roedores',
      rodentControlDesc: 'Inspección + plan dirigido. Inspección, monitoreo y recomendaciones de control de roedores basadas en las condiciones encontradas.',
      bedBugTreatment: 'Tratamiento de Chinches',
      bedBugTreatmentDesc: 'Tratamiento específico para la propiedad. Inspección y recomendaciones de tratamiento basadas en actividad confirmada y condiciones de la propiedad.',
      fleaTickTreatment: 'Tratamiento de Pulgas y Garrapatas',
      fleaTickTreatmentDesc: 'Tratamiento dirigido. Servicio enfocado para problemas de pulgas y garrapatas, con orientación de preparación cuando aplique.',
      mosquitoControl: 'Control de Mosquitos',
      mosquitoControlDesc: 'Servicio de mosquitos al aire libre. Tratamientos enfocados en áreas de descanso y cría al aire libre según las condiciones de la propiedad.',
      hoaPropertyManagement: 'HOA y Administración de Propiedades',
      hoaPropertyManagementDesc: 'Planes de servicio personalizados. Programación confiable, comunicación, servicio en áreas comunes y documentación para comunidades residenciales.',
    },
    whyVeritas: {
      title: '¿Por Qué Elegir Veritas?',
      subtitle: 'No somos solo otra empresa de control de plagas',
      reasons: [
        'Empresa familiar local sirviendo al Suroeste de Florida',
        'Técnicos licenciados, asegurados y certificados',
        'Opciones de tratamiento ecológicas y seguras para mascotas',
        'Precios transparentes sin cargos ocultos',
        'Garantía de satisfacción del 100% en todos los servicios',
        'Servicio de emergencia y mismo día disponible',
      ],
    },
    quickStart: {
      title: '¿Listo para Empezar?',
      subtitle: 'Cuéntenos Qué Ve',
      description: 'Obtenga su cotización gratuita y sin compromiso en menos de 2 minutos.',
      button: 'Obtener Mi Cotización Gratis',
    },
    process: {
      title: 'Nuestro Proceso Simple',
      subtitle: 'Empezar Es Fácil',
      steps: [
        { title: 'Inspección Gratis', description: 'Evaluamos su propiedad e identificamos problemas de plagas sin costo.' },
        { title: 'Plan Personalizado', description: 'Creamos un plan de tratamiento adaptado a sus necesidades específicas.' },
        { title: 'Tratamiento', description: 'Nuestros técnicos certificados aplican soluciones ecológicas.' },
        { title: 'Seguimiento', description: 'Regresamos para asegurar que las plagas se hayan ido y prevenir futuras.' },
      ],
    },
    hoa: {
      title: 'Administración de HOA y Comunidades',
      subtitle: 'Asóciese con Veritas para control de plagas comunitario confiable',
      badge: 'HOAs Y ADMINISTRADORES DE PROPIEDADES',
      description: 'Planes de servicio flexibles pueden incluir prevención programada de plagas, tratamiento de áreas comunes, monitoreo de estaciones de cebo para roedores, recomendaciones documentadas y términos de retrollamada definidos por acuerdo.',
      cta: 'Servicios para Comunidades y Administración de Propiedades',
      cardTitle: 'Diseñado para operaciones de propiedad',
      features: [
        'Precios por volumen para comunidades y HOAs',
        'Gerente de cuenta dedicado',
        'Tratamientos preventivos programados',
        'Informes de servicio detallados para juntas',
        'Respuesta de emergencia para áreas comunes',
        'Apoyo en comunicación con residentes',
      ],
    },
    serviceAreas: {
      title: 'Áreas que Servimos',
      subtitle: 'Orgullosamente sirviendo comunidades del Suroeste de Florida',
      areas: [
        { name: 'Fort Myers', description: 'Área de servicio principal.', link: '/services' },
        { name: 'San Carlos Park', description: 'Servicio local en el vecindario.', link: '/san-carlos-park' },
        { name: 'Estero', description: 'Opciones de control de plagas residencial.', link: '/estero' },
        { name: 'Bonita Springs', description: 'Opciones de control de plagas residencial.', link: '/bonita-springs' },
      ],
    },
    faq: {
      title: 'Preguntas Frecuentes',
      subtitle: 'Preguntas Frecuentes',
      questions: [
        {
          q: '¿Con qué frecuencia debo programar control de plagas?',
          a: 'Recomendamos tratamientos trimestrales para prevención óptima, pero ofrecemos servicios mensuales, bimensuales y únicos según sus necesidades.',
        },
        {
          q: '¿Sus tratamientos son seguros para mascotas y niños?',
          a: 'Sí, usamos productos aprobados por la EPA, ecológicos y seguros para su familia y mascotas una vez secos. También ofrecemos opciones totalmente orgánicas.',
        },
        {
          q: '¿Ofrecen servicios de emergencia?',
          a: 'Sí, proporcionamos servicio de emergencia y mismo día para problemas urgentes como nidos de avispas, infestaciones de roedores y más.',
        },
        {
          q: '¿Qué plagas tratan?',
          a: 'Tratamos hormigas, arañas, cucarachas, roedores, chinches, pulgas, garrapatas, mosquitos, termitas y más. Vea nuestra página de Servicios para la lista completa.',
        },
        {
          q: '¿Se requiere contrato?',
          a: 'No se requieren contratos para servicios únicos. Nuestros planes recurrentes son mes a mes sin cargos por cancelación.',
        },
      ],
    },
    cta: {
      title: 'No Deje que las Plagas Invadan su Hogar',
      subtitle: 'Obtenga Su Cotización Gratis de Control de Plagas',
      description: 'Únase a cientos de propietarios satisfechos del Suroeste de Florida que confían en Veritas para control de plagas confiable y efectivo.',
      button: 'Obtener Cotización Gratis',
    },
    footer: {
      tagline: 'INTEGRIDAD Y PROTECCIÓN',
      quickLinks: 'Enlaces Rápidos',
      services: 'Servicios',
      areas: 'Áreas de Servicio',
      contact: 'Contáctenos',
      phone: '(239) 227-0624',
      email: 'info@veritashomeservices.com',
      hours: 'Lun-Vie: 8am-6pm | Sáb: 9am-2pm',
      license: 'Licenciado y Asegurado • Licencia de Florida #JF123456',
      rights: 'Todos los derechos reservados.',
      description: 'Control de plagas residencial sirviendo Fort Myers, San Carlos Park, Estero, Bonita Springs y comunidades cercanas del Suroeste de Florida.',
      fortMyers: 'Fort Myers',
      sanCarlosPark: 'San Carlos Park',
      estero: 'Estero',
      bonitaSprings: 'Bonita Springs',
      hoasPropertyManagers: 'HOAs y Administradores de Propiedades',
      requestQuote: 'Solicitar Cotización',
      copyright: '© 2026 Veritas HomeServices LLC. Licencia de Negocio de Control de Plagas No. JB500621.',
      disclaimer: 'La disponibilidad, alcance y precios del servicio dependen de las condiciones de la propiedad y los términos de servicio escritos. El servicio de control de plagas está destinado a reducir y controlar la actividad de plagas cubiertas y no garantiza un ambiente completamente libre de plagas.',
    },
    quoteForm: {
      title: 'Obtenga Su Cotización Gratis',
      subtitle: 'Complete el formulario y le contactaremos en 24 horas',
      firstName: 'Nombre',
      lastName: 'Apellido',
      email: 'Correo Electrónico',
      phone: 'Teléfono',
      address: 'Dirección',
      city: 'Ciudad',
      zipCode: 'Código Postal',
      serviceType: 'Tipo de Servicio',
      propertyType: 'Tipo de Propiedad',
      pestIssues: 'Problemas de Plagas (seleccione todos los que apliquen)',
      preferredDate: 'Fecha Preferida',
      comments: 'Comentarios Adicionales',
      residential: 'Residencial',
      commercial: 'Comercial',
      submit: 'Enviar Solicitud de Cotización',
      submitting: 'Enviando...',
      success: '¡Gracias! Le contactaremos pronto.',
      error: 'Algo salió mal. Inténtelo de nuevo.',
      required: 'Requerido',
    },
    aiAssistant: {
      title: 'Asistente IA de Veritas',
      status: 'En línea',
      placeholder: 'Pregunte sobre plagas, servicios o precios...',
      quickReplies: [
        'Control de arañas - precios',
        'Detalles programa cucarachas alemanas',
        'Áreas de servicio cubiertas',
        'Solicitar cotización',
        'Horario de atención',
      ],
      quickRepliesAlt: [
        '¿Qué plagas tratan?',
        '¿Cuánto cuesta?',
        '¿Es seguro para mascotas?',
        '¿Ofrecen servicio de emergencia?',
        '¿Qué áreas sirven?',
      ],
      disclaimer: 'El asistente IA proporciona información general. Para asesoría específica, contacte a nuestro equipo.',
      initialMessage: "¡Hola! Soy el Asistente de Veritas. ¿Cómo puedo ayudarle con sus necesidades de control de plagas hoy?",
      toggleText: 'Asistente IA',
      closeLabel: 'Cerrar Asistente IA',
      openLabel: 'Abrir Asistente IA',
      sendLabel: 'Enviar mensaje',
      typingLabel: 'La IA está escribiendo...',
      callLabel: 'Llamar',
      botResponses: {
        spider: "El control exterior mensual de arañas comienza en $35/mes para propiedades residenciales calificadas. Incluye tratamiento exterior y eliminación de telarañas accesibles.",
        roach: "Nuestro programa de Eliminación de Cucarachas Alemanas es un programa estructurado de 4 visitas desde $225 para propiedades residenciales calificadas. El precio final depende del nivel de infestación y las condiciones de la propiedad.",
        area: "Servimos principalmente Fort Myers, San Carlos Park, Estero, Bonita Springs y comunidades cercanas del Suroeste de Florida.",
        quote: "Puede solicitar una cotización gratis usando nuestro formulario en línea o llamando/enviando mensaje al 239-227-0624. ¡Puedo ayudarle con eso!",
        hours: "Estamos disponibles Lunes-Viernes 8am-6pm, Sábado 8am-12pm. Para urgencias, llame al 239-227-0624.",
        bedBug: "El tratamiento de chinches es específico para cada propiedad. Comenzamos con una inspección y proporcionamos recomendaciones basadas en la actividad confirmada y las condiciones de  y proporcionamos recomendaciones basadas en la actividad confirmada y las condiciones de la propiedad.",
        rodent: "El control de roedores incluye inspección, monitoreo y recomendaciones dirigidas basadas en las condiciones encontradas. También ofrecemos monitoreo de estaciones de cebo para comunidades.",
        fleaTick: "El tratamiento de pulgas y garrapatas es un servicio enfocado con orientación de preparación cuando aplica. Tratamos según las condiciones específicas de su propiedad.",
        mosquito: "El control de mosquitos se enfoca en áreas de descanso y cría al aire libre según las condiciones de la propiedad. Es un servicio estacional para el Suroeste de Florida.",
        hoa: "Ofrecemos planes de servicio personalizados para HOAs y administradores de propiedades incluyendo prevención programada, tratamiento de áreas comunes, documentación y términos de retrollamada definidos por acuerdo.",
        default: "Puedo ayudar con precios, servicios, áreas de servicio, cotizaciones o preguntas generales. ¿Qué le gustaría saber?",
      },
    },
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('language');
    return saved || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = translations[language];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}